<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="user-PC" name="testcase_After_account_added.Social_after_added_Accounts" tests="10" failures="0" timestamp="24 Aug 2018 10:30:33 GMT" time="1120.201" errors="1">
  <testcase name="failedscrenshot" time="0.000" classname="testcase_After_account_added.Social_after_added_Accounts">
    <error type="org.testng.TestNGException" message="
Can inject only one of &lt;ITestContext, XmlTest&gt; into a @AfterTest annotated failedscrenshot.
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection">
      <![CDATA[org.testng.TestNGException: 
Can inject only one of <ITestContext, XmlTest> into a @AfterTest annotated failedscrenshot.
For more information on native dependency injection please refer to http://testng.org/doc/documentation-main.html#native-dependency-injection
at org.testng.internal.Parameters.checkParameterTypes(Parameters.java:407)
at org.testng.internal.Parameters.createParametersForMethod(Parameters.java:356)
at org.testng.internal.Parameters.createParameters(Parameters.java:635)
at org.testng.internal.Parameters.createConfigurationParameters(Parameters.java:190)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:209)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.TestRunner.afterRun(TestRunner.java:725)
at org.testng.TestRunner.run(TestRunner.java:509)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- failedscrenshot -->
  <testcase name="logintosynctag" time="38.607" classname="testcase_After_account_added.Social_after_added_Accounts"/>
  <testcase name="homefeeds" time="292.807" classname="testcase_After_account_added.Social_after_added_Accounts"/>
  <testcase name="friendsandfollowers" time="147.356" classname="testcase_After_account_added.Social_after_added_Accounts"/>
  <testcase name="timeline" time="278.856" classname="testcase_After_account_added.Social_after_added_Accounts"/>
  <testcase name="queue" time="92.332" classname="testcase_After_account_added.Social_after_added_Accounts"/>
  <testcase name="mailbox" time="41.425" classname="testcase_After_account_added.Social_after_added_Accounts"/>
  <testcase name="mentions" time="61.366" classname="testcase_After_account_added.Social_after_added_Accounts"/>
  <testcase name="xlporer" time="126.465" classname="testcase_After_account_added.Social_after_added_Accounts"/>
  <testcase name="archive" time="40.987" classname="testcase_After_account_added.Social_after_added_Accounts"/>
</testsuite> <!-- testcase_After_account_added.Social_after_added_Accounts -->
